# AESTHETIC config v0.3 — cleaned

extract:
  mode: hybrid
  per_scene_candidates: 9
  per_scene_keep: 3
  per_scene_keep_pct: 0.4
  min_scene_len_frames: 12
  min_candidate_gap_frames: 6

select:
  top_k: 6
  overcluster_factor: 4.0
  per_cluster_top: 2
  quality_floor: null

processing:
  resize_width: 720
  max_frames: 800

weights:
  technical: 0.5
  subjective: 0.5

sampling:
  jitter_frac: 0.12
  random_seed: 42

dedup:
  enable: false
  embed_min_cosine_dist: 0.02
  dhash: true
  dhash_threshold: 6
  per_scene_quota: 2

output:
  save_audits: true
  write_metrics_txt: true
  score_prefix: true
  folder: "aesthetic/outputs"

ffmpeg:
  bin: "C:\\ffmpeg\\bin\\ffmpeg.exe"
  probe: "C:\\ffmpeg\\bin\\ffprobe.exe"

logging:
  verbose: true
  save_log: true

models:
  clip: null

gpu:
  enabled: true
  device: "cuda:0"
  batch_size: 8

heavy:
  clip:
    enabled: true
    model: "ViT-B-32"
    precision: "fp16"     # keep fp32 as you set
    run_mode: "subprocess"      # subprocess -> inprocess fallback
    timeout_sec: 90

scenes:
  method: "content"       # "content" or "adaptive"
  threshold: 20.0
  downscale: 2

selector:
  use_clip_if_available: true
  dedup_clip_cosine_min: 0.02
